### ISSUE TITLE
[BUG] missing ) after argument list when using pnpm

### ISSUE THREAD

**Issue by JackBailey** [sibiraj-s/action-eslint#14]
I recently switched my repo to use pnpm, but it seems that this action no longer works with it.

Error log:
```
Run sibiraj-s/action-eslint@v3
Linting changed files.
Files for linting.
Files for linting.
/opt/hostedtoolcache/node/18.17.0/x64/bin/node /home/runner/work/Lynx/Lynx/src/node_modules/.bin/eslint src/modules/backup.js
/home/runner/work/Lynx/Lynx/src/node_modules/.bin/eslint:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.17.0
Error: The process '/opt/hostedtoolcache/node/18.17.0/x64/bin/node' failed with exit code 1
```

My workflow file: https://github.com/Lynx-Shortener/Lynx/blob/f8bb98c4a12fbdd376acdc62ced30f6b8b974b5f/.github/workflows/lint.yml

Running `node ./node_modules/.bin/eslint src/modules/backup.js` locally (Windows 11) I get the same problem, but running `eslint  src/modules/backup.js` it runs fine

**Comment by sibiraj-s** [comment]
To be honest I don't have much experience with Pnpm. Will look at it. Meanwhile PR's are welcome.

This is how the binary is executed. May be it needs to be updated for pnpm cases.

https://github.com/sibiraj-s/action-eslint/blob/bcf41bb9abce43cdbad51ab9b3da2eddaa17eab3/src/eslint.ts#L31

**Comment by JackBailey** [comment]
I'm taking a look at it, don't have much experience with tsc or creating actions but I believe this should do it:
https://github.com/JackBailey/action-eslint/commit/33e4c37752d8be96ab965cc5f26e4321b87f49c3

Just trying to test it now

Then the option eslint-command can be set to just `eslint`, otherwise it'll fall back to `node_modules/.bin/eslint`
